The issue here is that the `test_file` contains incorrect syntax. The correct syntax for adding a new project to CMakeLists.txt should start with `<project>` and then specify the source of your project (which in this case is `/third_party/googletest/googletest`). Here's how you can fix it:

```c
#include <gtest/gtest.h>
#include "Jwt.h"
#include "drogon/drogon.h"

// The 'drogon' header should be present in the test's input_dir for Drogon to recognize it as an import project.

TEST(TestJwt, Test1) {
  // Given that there is no secret passed
  auto jwt = jwt::Jwt(jwt::secret, jwt::sessionTime, "test");
  
  // Then the JWT token should be equal to the jwtToken (generated by Drogon)
  EXPECT_EQ(jwt.encode("name", "user").payload(), jwt.encode("name", "user"));
}

TEST(TestJwt, Test2) {
  // Given that there is no secret passed
  auto jwt = jwt::Jwt(jwt::secret, jwt::sessionTime, "test");

  // Then the JWT token should be equal to the jwtToken (generated by Drogon)
  EXPECT_EQ(jwt.encode("name", "user").payload(), jwt.encode("name", "user"));
}

TEST(TestJwt, Test3) {
  // Given that there is no secret passed
  auto jwt = jwt::Jwt(jwt::secret, jwt::sessionTime, "test");

  // Then the JWT token should be equal to the jwtToken (generated by Drogon)
  EXPECT_EQ(jwt.encode("name", "user").payload(), jwt.encode("name", "user"));
}

TEST(TestJwt, Test4) {
  auto jwt = jwt::Jwt(jwt::secret, jwt::sessionTime, "test");

  // This should fail because the session time is not specified
  EXPECT_THROW(testToken(), std::runtime_error);
}
```

This should now be correct.

